### ISSUE TITLE
How to validate phrases?

### ISSUE THREAD

**Issue by oltarasenko** [AgileAlpha/block_keys#17]
One of the tasks I need to build is being able to generate keys from the phrases sent by clients from outside. 

What I have noticed that my phrases generated by `BlockKeys.Mnemonic.generate_phrase` the function would allow me to generate seeds used for keys generation.

However I am trying to understand how to validate phrases from external systems, so they can be used by us. For example:

```
iex(27)> phrase = BlockKeys.Mnemonic.generate_phrase
"shuffle clay veteran vicious achieve regular mammal regular pluck income crack client oxygen unaware plate client expire eager glimpse limit wonder dentist access naive"
iex(28)> BlockKeys.Mnemonic.generate_seed(phrase)
"a1425bc1452ae8a9ef9a1743daa8164657bf60003170fc32faa9b1cf34f90c52e44c6bb3da66b38b2af333d71219b1eab41c147c0b2b272f5612949e9affadb7"
```
Works

However when I have changed something in the phrase (e.g. I am assuming that the user have sent us something different)
```
# See I have replaced the first word to clay here...
iex(30)> phrase = "clay clay veteran vicious achieve regular mammal regular pluck income crack client oxygen unaware plate client expire eager glimpse limit wonder dentist access naive"
"clay clay veteran vicious achieve regular mammal regular pluck income crack client oxygen unaware plate client expire eager glimpse limit wonder dentist access naive"
iex(31)> BlockKeys.Mnemonic.generate_seed(phrase)                                                     
{:error, "Checksum is not valid"}

# See I have removed two first words here
iex(32)> phrase = "veteran vicious achieve regular mammal regular pluck income crack client oxygen unaware plate client expire eager glimpse limit wonder dentist access naive"
"veteran vicious achieve regular mammal regular pluck income crack client oxygen unaware plate client expire eager glimpse limit wonder dentist access naive"
iex(33)> BlockKeys.Mnemonic.generate_seed(phrase)                                                      
** (FunctionClauseError) no function clause matching in BlockKeys.Mnemonic.verify_checksum/1

    The following arguments were given to BlockKeys.Mnemonic.verify_checksum/1:

        # 1
        <<243, 62, 112, 7, 90, 104, 107, 105, 169, 171, 148, 49, 197, 90, 121, 118, 58,
          98, 85, 148, 26, 39, 99, 48, 63, 244, 29, 64, 21, 37>>

    Attempted function clauses (showing 1 out of 1):

        defp verify_checksum(<<entropy::binary()-size(32), checksum::binary()-size(1)>>)

    (block_keys 0.1.5) lib/block_keys/mnemonic.ex:151: BlockKeys.Mnemonic.verify_checksum/1
    (block_keys 0.1.5) lib/block_keys/mnemonic.ex:66: BlockKeys.Mnemonic.generate_seed/2
iex(33)>
```

Could you explain how do I understand which phrase is correct and which is not?

**Comment by tzumby** [comment]
Hey @oltarasenko. So the reason changing a few words fails the checksum is because the last two words in the phrase are not random, but encode the checksum of the rest of the phrase. This means that if you change `shuffle` with `clay`, you also have to update `naive` (the last word) to match the new checksum word mapping. 

The second pattern match error is a shortcoming of this library. It assumes the input is 32bits when verifying the checksum - that's because I didn't account for less than 24 words initially. I'm totally down to make this more flexible, so I can work on fixing this to support shorter phrases. At least the checksum is easy, we might have to pad the entropy (repeat the sequence) if you only provide say 3 words.

**Comment by tzumby** [comment]
Did some more digging into this. My previous comment still stands, the library is not properly creating / checking the checksum for 12 word mnemonics (16bits entropy). That's a bug and I will fix it shortly.

For mnemonics less than 12 words we can't generate a checksum because the checksum size would be less than 4 bits and not enough for a word. I will update the `generate_seed/1` to skip the `verify_checksum/1` if we have less than 12 mnemonics.
