### ISSUE TITLE
Not working on Elixir 1.10.3 / OTP 23

### ISSUE THREAD

**Issue by felipelincoln** [AgileAlpha/block_keys#33]
I cloned this repository, then ran  `mix deps.get` and `iex -S mix`:

```
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> root_key = BlockKeys.from_mnemonic("nurse grid sister metal flock choice system control about mountain sister rapid hundred render shed chicken print cover tape sister zero bronze tattoo stairs")
"xprv9s21ZrQH143K35qGjQ6GG1wGHFZP7uCZA1WBdUJA8vBZqESQXQGA4A9d4eve5JqWB5m8YTMcNe8cc7c3FVzDGNcmiabi9WQycbFeEvvJF2D"
iex(2)> BlockKeys.CKD.derive(root_key, "M/44'/60'/0'/0/0") |> BlockKeys.Ethereum.Address.from_xpub

21:58:12.955 [warn]  The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'/home/felipe/local-repositories/block_keys/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so: cannot open shared object file: No such file or directory\''}}

** (UndefinedFunctionError) function :libsecp256k1.ec_pubkey_create/2 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.1.10) :libsecp256k1.ec_pubkey_create(<<52, 229, 119, 241, 177, 34, 46, 53, 218, 61, 119, 101, 81, 208, 34, 9, 178, 233, 180, 154, 141, 245, 203, 159, 179, 170, 124, 150, 195, 100, 32, 80>>, :uncompressed)
    (block_keys 0.1.10) lib/block_keys/crypto.ex:26: BlockKeys.Crypto.public_key/1
    (block_keys 0.1.10) lib/block_keys/ckd.ex:202: BlockKeys.CKD.put_uncompressed_parent_pub/2
    (block_keys 0.1.10) lib/block_keys/ckd.ex:82: BlockKeys.CKD.child_key_private/2
    (block_keys 0.1.10) lib/block_keys/ckd.ex:55: BlockKeys.CKD._derive/2
    (block_keys 0.1.10) lib/block_keys/ckd.ex:28: BlockKeys.CKD.derive/2
iex(2)> 
```

**Comment by felipelincoln** [comment]
Fixed after installing automake, libtool, inotify-tools and autoconf
